### PR TITLE
Bugfix/dbnl book chapter order

### LINKED ISSUE #1494: DBNL: "view book" shows reverse chapter order
### What went wrong?

Documents in the DBNL corpus show a "view book" link, which is supposed to show all chapters from that book in order. Instead, the chapters are shown in _descending_ order, starting with the last chapter.

### What did you expect to happen?

The chapters should be shown in _ascending_ order.

### Screenshot

_No response_

### Where did you find the bug?

- https://ianalyzer.hum.uu.nl
-  a local server

### Version

5.5.0

### Steps to reproduce

- Go to a document in DBNL, e.g. https://ianalyzer.hum.uu.nl/document/dbnl/meer017tone02_01_0041
- Click "view book"

### PR DESCRIPTION
**Pull request by lukavdplas**
- The 'view book' link for DBNL now shows chapters in the correct order (close #1494)
- Fixes an issue when opening a link with ascending sort direction (which was reset to descending)
- The document popup now closes when you click the context link for a document.

### CODE REVIEW

File: frontend/src/app/document/document-popup/document-popup.component.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
 import { DocumentFocus, DocumentPage, DocumentView } from '../../models/document-page';
-import { takeUntil } from 'rxjs/operators';
+import { takeUntil, tap } from 'rxjs/operators';
```
Comment (BeritJanssen) [inline frontend/src/app/document/document-popup/document-popup.component.ts:3]: unused import.

**Review by BeritJanssen — APPROVED** [review]
LGTM
